application: <your application id>
version: 1
runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /cron/tweet
  script: crontweethandler.app
  login: admin
- url: /task/tweet/.*
  script: tasktweethandler.app
  login: admin
- url: /task/errormail
  script: taskerrormailhandler.app
  login: admin
- url: /feed
  script: feedhandler.app
libraries:
- name: lxml
  version: latest
- name: django
  version: latest
